name: Hello World Workflow

on:
  push:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:
    inputs:
      username:
        description: "Enter your name"
        required: true
        default: "Name"

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Print greeting
        run: echo "Hello ${{ github.event.inputs.username || 'User' }}"

      - name: Echo current time
        run: echo "The current server time is $(date)"
